### ISSUE TITLE
Support pre-installing applications from a template file on first XP boot

### ISSUE THREAD

**Issue by pmi** [enonic/app-xp-welcome#241]
- Parse list of apps in `main.js`
- Create task for each app
- Task should get app url and icon, download and install it
- Home screen should display greyed-out app for every task
- There should be progress bar below each app showing task progress
- When installation is done the app should become colorized 
```[tasklist]
### Tasks
- [ ] https://github.com/enonic/app-xp-welcome/issues/248
- [ ] #249
- [ ] #250
- [ ] https://github.com/enonic/app-xp-welcome/issues/251
- [ ] https://github.com/enonic/app-xp-welcome/issues/252
- [ ] https://github.com/enonic/app-xp-welcome/issues/253
- [ ] https://github.com/enonic/app-xp-welcome/issues/254
- [ ] https://github.com/enonic/app-xp-welcome/issues/264
- [ ] https://github.com/enonic/app-xp-welcome/issues/265
- [ ] https://github.com/enonic/app-xp-welcome/issues/272
```

**Comment by pmi** [comment]
1. Parse list of apps in `main.js`
2. Create task for each app
3. Task should get app url and icon, download and install it
4. Home screen should display greyed-out app for every task
5. There should be progress bar below each app showing task progress
6. When installation is done the app should become colorized
